import { getDb } from '../client';
import { metricDefinitions, unitConversions } from '../schema/metrics';
import { shareTemplates } from '../schema/sharing';

async function main() {
  const db = getDb();

  console.log('Seeding metric definitions...');
  await db
    .insert(metricDefinitions)
    .values([
      {
        id: 'glucose',
        name: 'Glucose',
        category: 'metabolic',
        unit: 'mg/dL',
        loincCode: '2345-7',
        aliases: ['blood sugar', 'blood glucose', 'fasting glucose', 'FBG'],
        referenceRangeLow: 70,
        referenceRangeHigh: 100,
        referenceRangeText: '70-100 mg/dL (fasting)',
        description: 'Fasting blood glucose level',
        sortOrder: 1,
      },
      {
        id: 'hemoglobin_a1c',
        name: 'Hemoglobin A1c',
        category: 'metabolic',
        unit: '%',
        loincCode: '4548-4',
        aliases: ['HbA1c', 'A1C', 'glycated hemoglobin', 'glycosylated hemoglobin'],
        referenceRangeLow: 4.0,
        referenceRangeHigh: 5.6,
        referenceRangeText: '< 5.7% (normal)',
        description: 'Average blood sugar over past 2-3 months',
        sortOrder: 2,
      },
      {
        id: 'cholesterol_total',
        name: 'Total Cholesterol',
        category: 'lipid',
        unit: 'mg/dL',
        loincCode: '2093-3',
        aliases: ['cholesterol', 'total cholesterol', 'TC'],
        referenceRangeLow: 0,
        referenceRangeHigh: 200,
        referenceRangeText: '< 200 mg/dL (desirable)',
        description: 'Total blood cholesterol level',
        sortOrder: 10,
      },
      {
        id: 'ldl_cholesterol',
        name: 'LDL Cholesterol',
        category: 'lipid',
        unit: 'mg/dL',
        loincCode: '2089-1',
        aliases: ['LDL', 'LDL-C', 'bad cholesterol'],
        referenceRangeLow: 0,
        referenceRangeHigh: 100,
        referenceRangeText: '< 100 mg/dL (optimal)',
        description: 'Low-density lipoprotein cholesterol',
        sortOrder: 11,
      },
      {
        id: 'hdl_cholesterol',
        name: 'HDL Cholesterol',
        category: 'lipid',
        unit: 'mg/dL',
        loincCode: '2085-9',
        aliases: ['HDL', 'HDL-C', 'good cholesterol'],
        referenceRangeLow: 40,
        referenceRangeHigh: 60,
        referenceRangeText: '> 40 mg/dL (men), > 50 mg/dL (women)',
        description: 'High-density lipoprotein cholesterol',
        sortOrder: 12,
      },
      {
        id: 'triglycerides',
        name: 'Triglycerides',
        category: 'lipid',
        unit: 'mg/dL',
        loincCode: '2571-8',
        aliases: ['TG', 'trigs'],
        referenceRangeLow: 0,
        referenceRangeHigh: 150,
        referenceRangeText: '< 150 mg/dL (normal)',
        description: 'Blood triglyceride level',
        sortOrder: 13,
      },
      {
        id: 'tsh',
        name: 'TSH',
        category: 'thyroid',
        unit: 'mIU/L',
        loincCode: '11580-8',
        aliases: ['thyroid stimulating hormone', 'thyrotropin'],
        referenceRangeLow: 0.4,
        referenceRangeHigh: 4.0,
        referenceRangeText: '0.4-4.0 mIU/L',
        description: 'Thyroid stimulating hormone',
        sortOrder: 20,
      },
      {
        id: 'free_t4',
        name: 'Free T4',
        category: 'thyroid',
        unit: 'ng/dL',
        loincCode: '3024-7',
        aliases: ['FT4', 'free thyroxine', 'thyroxine'],
        referenceRangeLow: 0.8,
        referenceRangeHigh: 1.8,
        referenceRangeText: '0.8-1.8 ng/dL',
        description: 'Free thyroxine level',
        sortOrder: 21,
      },
      {
        id: 'creatinine',
        name: 'Creatinine',
        category: 'renal',
        unit: 'mg/dL',
        loincCode: '2160-0',
        aliases: ['creat', 'serum creatinine', 'SCr'],
        referenceRangeLow: 0.6,
        referenceRangeHigh: 1.2,
        referenceRangeText: '0.6-1.2 mg/dL',
        description: 'Serum creatinine for kidney function',
        sortOrder: 30,
      },
      {
        id: 'bun',
        name: 'BUN',
        category: 'renal',
        unit: 'mg/dL',
        loincCode: '3094-0',
        aliases: ['blood urea nitrogen', 'urea nitrogen'],
        referenceRangeLow: 7,
        referenceRangeHigh: 20,
        referenceRangeText: '7-20 mg/dL',
        description: 'Blood urea nitrogen',
        sortOrder: 31,
      },
      {
        id: 'sodium',
        name: 'Sodium',
        category: 'electrolyte',
        unit: 'mEq/L',
        loincCode: '2951-2',
        aliases: ['Na', 'Na+', 'serum sodium'],
        referenceRangeLow: 136,
        referenceRangeHigh: 145,
        referenceRangeText: '136-145 mEq/L',
        description: 'Serum sodium level',
        sortOrder: 40,
      },
      {
        id: 'potassium',
        name: 'Potassium',
        category: 'electrolyte',
        unit: 'mEq/L',
        loincCode: '2823-3',
        aliases: ['K', 'K+', 'serum potassium'],
        referenceRangeLow: 3.5,
        referenceRangeHigh: 5.0,
        referenceRangeText: '3.5-5.0 mEq/L',
        description: 'Serum potassium level',
        sortOrder: 41,
      },
      {
        id: 'calcium',
        name: 'Calcium',
        category: 'electrolyte',
        unit: 'mg/dL',
        loincCode: '17861-6',
        aliases: ['Ca', 'serum calcium', 'total calcium'],
        referenceRangeLow: 8.5,
        referenceRangeHigh: 10.5,
        referenceRangeText: '8.5-10.5 mg/dL',
        description: 'Serum calcium level',
        sortOrder: 42,
      },
      {
        id: 'vitamin_d',
        name: 'Vitamin D',
        category: 'vitamin',
        unit: 'ng/mL',
        loincCode: '1989-3',
        aliases: ['25-OH vitamin D', 'calcidiol', '25-hydroxyvitamin D', 'vit D'],
        referenceRangeLow: 30,
        referenceRangeHigh: 100,
        referenceRangeText: '30-100 ng/mL (sufficient)',
        description: '25-hydroxyvitamin D level',
        sortOrder: 50,
      },
      {
        id: 'iron',
        name: 'Iron',
        category: 'iron_study',
        unit: 'mcg/dL',
        loincCode: '2498-4',
        aliases: ['serum iron', 'Fe'],
        referenceRangeLow: 60,
        referenceRangeHigh: 170,
        referenceRangeText: '60-170 mcg/dL',
        description: 'Serum iron level',
        sortOrder: 51,
      },
      {
        id: 'ferritin',
        name: 'Ferritin',
        category: 'iron_study',
        unit: 'ng/mL',
        loincCode: '2276-4',
        aliases: ['serum ferritin'],
        referenceRangeLow: 12,
        referenceRangeHigh: 300,
        referenceRangeText: '12-300 ng/mL (men), 12-150 ng/mL (women)',
        description: 'Serum ferritin level (iron stores)',
        sortOrder: 52,
      },
      {
        id: 'wbc',
        name: 'White Blood Cell Count',
        category: 'hematology',
        unit: 'K/uL',
        loincCode: '6690-2',
        aliases: ['WBC', 'white blood cells', 'leukocytes', 'white count'],
        referenceRangeLow: 4.5,
        referenceRangeHigh: 11.0,
        referenceRangeText: '4.5-11.0 K/uL',
        description: 'White blood cell count',
        sortOrder: 60,
      },
      {
        id: 'rbc',
        name: 'Red Blood Cell Count',
        category: 'hematology',
        unit: 'M/uL',
        loincCode: '789-8',
        aliases: ['RBC', 'red blood cells', 'erythrocytes', 'red count'],
        referenceRangeLow: 4.5,
        referenceRangeHigh: 5.5,
        referenceRangeText: '4.5-5.5 M/uL (men), 4.0-5.0 M/uL (women)',
        description: 'Red blood cell count',
        sortOrder: 61,
      },
      {
        id: 'hemoglobin',
        name: 'Hemoglobin',
        category: 'hematology',
        unit: 'g/dL',
        loincCode: '718-7',
        aliases: ['Hgb', 'Hb'],
        referenceRangeLow: 12.0,
        referenceRangeHigh: 17.5,
        referenceRangeText: '13.5-17.5 g/dL (men), 12.0-16.0 g/dL (women)',
        description: 'Hemoglobin concentration',
        sortOrder: 62,
      },
      {
        id: 'hematocrit',
        name: 'Hematocrit',
        category: 'hematology',
        unit: '%',
        loincCode: '4544-3',
        aliases: ['Hct', 'HCT', 'crit', 'packed cell volume'],
        referenceRangeLow: 36,
        referenceRangeHigh: 52,
        referenceRangeText: '38.3-48.6% (men), 35.5-44.9% (women)',
        description: 'Percentage of blood volume occupied by red blood cells',
        sortOrder: 63,
      },
      {
        id: 'platelets',
        name: 'Platelet Count',
        category: 'hematology',
        unit: 'K/uL',
        loincCode: '777-3',
        aliases: ['PLT', 'thrombocytes', 'platelet count'],
        referenceRangeLow: 150,
        referenceRangeHigh: 400,
        referenceRangeText: '150-400 K/uL',
        description: 'Platelet count',
        sortOrder: 64,
      },
    ])
    .onConflictDoNothing();

  console.log('Seeding share templates...');
  await db
    .insert(shareTemplates)
    .values([
      {
        id: 'clinician',
        name: 'Clinician',
        description: 'Full clinical data sharing for your doctor or specialist',
        categories: [
          'lab_result',
          'vital_sign',
          'medication',
          'condition',
          'encounter',
          'imaging',
          'dental',
          'wearable',
        ],
        defaultAccessLevel: 'view_download',
        sortOrder: 1,
      },
      {
        id: 'nutritionist',
        name: 'Nutritionist',
        description: 'Lab results, vitals, and medications for dietary guidance',
        categories: ['lab_result', 'vital_sign', 'medication'],
        defaultAccessLevel: 'view',
        sortOrder: 2,
      },
      {
        id: 'fitness_coach',
        name: 'Fitness Coach',
        description: 'Vital signs and wearable data for training optimization',
        categories: ['vital_sign', 'wearable'],
        defaultAccessLevel: 'view',
        sortOrder: 3,
      },
      {
        id: 'family',
        name: 'Family Member',
        description: 'Key health information for a trusted family member',
        categories: ['lab_result', 'vital_sign', 'medication', 'condition'],
        defaultAccessLevel: 'view',
        sortOrder: 4,
      },
      {
        id: 'dental',
        name: 'Dental Provider',
        description: 'Dental and encounter records for your dentist',
        categories: ['dental', 'encounter'],
        defaultAccessLevel: 'view',
        sortOrder: 5,
      },
    ])
    .onConflictDoNothing();

  console.log('Seeding unit conversions...');
  await db
    .insert(unitConversions)
    .values([
      {
        fromUnit: 'mg/dL',
        toUnit: 'mmol/L',
        metricCode: 'glucose',
        multiplier: 0.0555,
        offset: 0,
      },
      {
        fromUnit: 'mg/dL',
        toUnit: 'mmol/L',
        metricCode: 'cholesterol_total',
        multiplier: 0.0259,
        offset: 0,
      },
      {
        fromUnit: 'lb',
        toUnit: 'kg',
        metricCode: null,
        multiplier: 0.4536,
        offset: 0,
      },
      {
        fromUnit: 'in',
        toUnit: 'cm',
        metricCode: null,
        multiplier: 2.54,
        offset: 0,
      },
      {
        fromUnit: 'F',
        toUnit: 'C',
        metricCode: null,
        multiplier: 0.5556,
        offset: -17.7778,
      },
    ])
    .onConflictDoNothing();

  console.log('Seed completed successfully.');
}

main()
  .then(() => {
    process.exit(0);
  })
  .catch((error) => {
    console.error('Seed failed:', error);
    process.exit(1);
  });
